// tests for dummy
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha')
const expect = mochaPlugin.chai.expect
let wrapped = mochaPlugin.getWrapper('dummy', '../../../src/functions/dummy.js', 'dummy')
const AWS = require('aws-sdk-mock')
const AWS_SDK = require('aws-sdk')
AWS.setSDKInstance(AWS_SDK)
describe('dummy', () => {
	before((done) => {
		done()
	})

	it('implement tests here', async () => {
		const response = await wrapped.run({})
		expect(response).to.not.be.empty
	})
})
